server:
  port: 9002

eureka:
  instance:
    hostname: eureka9002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/  # 相互注册,这里写 eureka9001.com