spring:
  application:
    name: e-commerce-gateway
  cloud:
    gateway:
      #配置路由, 可以有多个路由配置 List<RouteDefinition> routes
      routes:
        - id: member_route01   #路由的 ID，程序员自己写,要求唯一
          #gateway 最终访问的 url = uri+Path 即: http://localhost:10002/memeber/get/
          #匹配后提供服务的路由地址, 也可以是外网 uri,比如 http://www.qq.com 等
          uri: http://localhost:10002
          predicates:
            - Path=/member/get/**
        - id: member_route02
          uri: http://localhost:10002
          predicates:
            - Path=/member/save

eureka:
  instance:
    hostname: e-commerce-service
  client:
    enabled: false
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka9001.com:9001/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
    org.springframework.http.server.reactive: TRACE

server:
  port: 20000
