monster:
  id: 100
  name: 牛魔
  age: 500
  isMarried: true
  birth: 2000/11/11
  car: {name:宝马, price:99999999}  # 行内格式
#  car:
#    name: 宝马
#    price: 9999999.9
  skill:
    - 铁拳
    - 牛角
  hobby: [喝酒, 吃肉]
#  wife: {key01:狐狸精, key02:铁扇公主}
  wife:
    no1: 狐狸精
    no2: 铁扇公主
  salaries:
    - 100
    - 200
  cars:  # k-v  v:List<Car>
    grade01:
      - { name: 保时捷, price: 999999 }  # 行内风格
      - name: 法拉利  # 换行风格
        price: 888888.88
    grade02:
      - { name: 宝马, price: 200000 }
      - name: 奥迪
        price: 88888.3

#TODO 配置静态资源访问路径为/qiaolezi/**   (ori: /**)
spring:
  servlet:
    multipart:  # 设置上传文件的大小
      max-file-size: 10MB
      max-request-size: 50MB
  mvc:
    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true  # 启用HiddenHttpMethodFilter
    view:
      prefix: /   # 这里需要和当前的static-path-pattern一致
      suffix: .html
    contentnegotiation:
      favor-parameter: true  # 开启基于请求参数的内容协商功能
  web:
    resources:
      # 这里指定的话，会覆盖掉原来的路径，所以需要把原来的也加上
      static-locations: ["classpath:/img/","classpath:/META-INF/resources/","classpath:/resources/", "classpath:/static/", "classpath:/public/" ]