server:
  port: 80

spring:
  application:
    name: member-service-consumer-openfeign

#eureka 客户端配置
eureka:
  client:
    register-with-eureka: true #将自己注册到 EurekaServer
    fetchRegistry: true #配置从 EurekaServer 抓取其它服务注册信息
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka, http://eureka9002.com:9002/eureka

#ribbon:
#  #设置 feign 客户端超时时间（openFeign 默认支持 ribbon)
#  #指的是建立连接后从服务器读取到可用资源所用的时间，
#  #时间单位是毫秒
#  ReadTimeout: 8000
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下，
#  #两端连接所用的时间
#  ConnectTimeout: 8000


#logging:
#  level:
#    #对 MemberFeignService 接口调用过程 打印的日志信息-debug 级别
#      #error：错误日志，指比较严重的错误，对正常业务有影响，需要运维配置监控的
#      #warn：警告日志，一般的错误，对业务影响不大，但是需要开发关注；
#      #info：信息日志，记录排查问题的关键信息，如调用时间、出参入参等等；
#      #debug：用于开发 DEBUG 的，关键逻辑里面的运行时数据；
#      #trace：最详细的信息，一般这些信息只记录到日志文件中。
#    qlz.spring_cloud.service.MemberFeignService: debug